version: '3.8'

networks:
  isolation-network:
    driver: bridge

services:
  classification_inference:
    build:
      context: ./classification_inference
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8088
    ports:
      - 8088:8088
    depends_on:
      - server
    restart: always
    networks:
      - isolation-network
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - isolation-network
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - isolation-network
volumes:
  postgres_data:
